[package]
name = "nightmare"
version = "0.1.0"
edition = "2024"


[dependencies]
anyhow = "1.0.98"
case = "1.0.0"
deno_ast = { version = "0.35.0", features = ["transpiling", "view"] }
tree-sitter = { version = "0.25.6", features = ["wasm", "wasmtime-c-api"] }
tree-sitter-typescript = "0.23.2"



